name: CI
on:
  pull_request: {}
  merge_group: {}
  push: {}

jobs:
  build-vm:
    name: Build image ${{ matrix.image }}-${{ matrix.arch.name }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        image:
          - ubuntu
        arch:
          - name: x86_64
            mode: host

    env:
      IMAGE_NAME: ${{ matrix.image }}
      IMAGE_ARCH: ${{ matrix.arch.name }}
      IMAGE_MODE: ${{ matrix.arch.mode }}
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v7.0.1

      - name: Install Packer
        uses: hashicorp/setup-packer@ce93c3c08a6c2ff2275bf4b54ff0d9a75f6c9789 # v3.4.0

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::442426873467:role/gha-self-hosted-images-upload

      - name: Build the image
        run: |
          packer init aws-ubuntu.pkr.hcl
          packer build -var "ami_name=packer-test-$(openssl rand -hex 15)" aws-ubuntu.pkr.hcl
        env:
          # This token is only needed to bypass the rate limit when downloading Packer plugins. The
          # token only has read-only access to repository contents anyway, so there is no risk
          # passing it to Packer.
          # FIXME: This is no longer read-only.
          PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  finish:
    name: CI finished
    runs-on: ubuntu-latest
    permissions: {}
    if: "${{ !cancelled() }}"
    needs:
      - build-vm
    steps:
      - name: Check if all jobs were successful or skipped
        run: echo "${NEEDS}" | jq --exit-status 'all(.result == "success" or .result == "skipped")'
        env:
          NEEDS: "${{ toJson(needs) }}"
